### ISSUE TITLE
Add CoC/contributing.md

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/.github#3]
CoCs and contributing.mds are currently located in `docs/` folders in each repo. Should we centralize those in `.github` as well?

**Comment by slifty** [comment]
Definitely for CoC.
Probably for Contributing.  The only question about Contributing is how to handle things like "guidance on migrations" -- we could probably update it to say things like "if the project as migrations" rather than "this project has migrations".

Can we also port TESTING.md or does it have to be special approve-listed files that github supports?

**Comment by chriszs** [comment]
TESTING.md isn't one of the "[supported file types](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types)." My guess is you could add it to a centralized repo, maybe this one or meta, and then link to it from other docs, like README or CONTRIBUTING, but I don't think GitHub automatically picks it up to link anywhere in the interface? Could be wrong on that.

**Comment by reefdog** [comment]
IMO we shouldn't shy away from centralizing boilerplate here even if GitHub doesn't magically link it to other repos.

If that boilerplate is sufficiently generic we could link to it here (as mentioned), but I don't think we should shy away from copying the centralized boilerplate into the new repo when instructions differ. (In other words, detailed repo-specific TESTING.md beats a painfully generic TESTING.md.)

CONTRIBUTING does seem like it should mostly be about generic process / best practices, and we should have repo-specific instructions for setup/testing/etc.
